dir.create(file.path("data"))
dir.create(file.path("raw-data"))
dir.create(file.path("raw-annotations"))
dir.create(file.path("raw-selections"))
dir.create(file.path("edited-selections"))
dir.create(file.path("wdata"))
